### ISSUE TITLE
Make search queries replace spaces with + or %20

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/seattle_v2#41]
URL encoding standards are to replace spaces with a `+` or `%20`. Currently when search queries include multiple words they produce broken URLs which cant be shared properly.

https://councildataproject.github.io/seattle/#/search?q=green new deal

Should be either:

https://councildataproject.github.io/seattle/#/search?q=green+new+deal
https://councildataproject.github.io/seattle/#/search?q=green%20new%20deal

I personally prefer the `+` but doesn't really matter imo.

**Comment by tohuynh** [comment]
> URL encoding standards are to replace spaces with a `+` or `%20`. Currently when search queries include multiple words they produce broken URLs which cant be shared properly.
> 
> https://councildataproject.github.io/seattle/#/search?q=green new deal
> 
> Should be either:
> 
> https://councildataproject.github.io/seattle/#/search?q=green+new+deal
> https://councildataproject.github.io/seattle/#/search?q=green%20new%20deal
> 
> I personally prefer the `+` but doesn't really matter imo.

For me, on Chrome, `%20` is added.
But on Firefox, it doesn't get added.
I will add in the '+' to the URLs
