### ISSUE TITLE
Add share link at timepoint functionality

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/seattle_v2#49]
YouTube has a great feature of "Copy video URL at current time" which would be amazing to have for our event pages. Allowing people to share links that jump to the portion of the meeting they are interested in would be amazing.

Last time we looked into this the limited factor was that the delay between the database retrieval and content load was too large but I think we can add more info to the encoded URL and add a "on video ready" hook that uses the info encoded in the URL to jump.

Where to position this button and how it's styled is another thing.

**Comment by tohuynh** [comment]
I'm liking the share button of YouTube, which opens a modal with content on how to share video at a time point. Lets have the share button float to the right of the meeting date. But should it be below or on top of the video?

Just a first thought, the URL could be appended with ?t={videoTimePoint}.
Then `video-react` Player has a `startTime` prop, which will seek to `videoTimePoint` on video load.

**Comment by evamaxfield** [comment]
Agree, modal looks nice. I think share button should float on the right side of the "EventTabs" as basically another tab but just floated to the right. Idk, I can see your way and mine, hard to know without seeing it I guess.

Agree on URL appended with `?t={videoTimePoint}` and excellent that `video-react` _should_ handle this for us :+1:

**Comment by evamaxfield** [comment]
I am tempted to also say, if `?t=` is appended to URL the page should jump to that transcript portion too. Thoughts?

**Comment by tohuynh** [comment]
![image](https://user-images.githubusercontent.com/37560480/71634493-573d0f00-2bd1-11ea-89db-4aeef3bd1292.png)

Just added a button on top of the video, what do you think?

**Comment by tohuynh** [comment]
Do you mean jump to the transcript portion in EventTabs or in Search Transcript?

**Comment by tohuynh** [comment]
If the share button is added to "EventTabs", the button could be far away from video on mobile.
Because initially, when video is not sticky, on mobile the UI is video, Search transcript, then EventTabs.
There will be a distance between the video and the share button.

**Comment by evamaxfield** [comment]
Ahhhhh good points on mobile accessibility and thanks for the screenshot. I like the placement there so let's go with that placement.

On the transcript portion I mean the EventTabs transcript.

**Comment by tohuynh** [comment]
> On the transcript portion I mean the EventTabs transcript.

I _believe_ this could be done, jumping to that particular sentence of `videoTimePoint`. But I won't add this feature for this issue. It's probably a good idea to figure out #51 first and then add that piece of code.

**Comment by evamaxfield** [comment]
Sounds good! :+1:
