### ISSUE TITLE
Add timestamped speaker turns to event page

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/seattle_v2#51]
In light of [#101](https://github.com/CouncilDataProject/cdptools/pull/101), the front-end of transcripts should be updated to show new `timestamped-speaker-turns` format.

I'm thinking maybe group the sentences together for a speaker turn block. That is, just add a horizontal line between each speaker turn block. If there's a speaker, show that above each speaker turn block.

I think the transcript under Search Transcript can remain the same, regardless of formats.

**Comment by evamaxfield** [comment]
Agree on all fronts.

**Comment by evamaxfield** [comment]
Similar to the backend PR linked, I would make it a try catch. Or if you wanted to be really fancy, have a transcript renderer map. Where given the transcript format string it returns the content ready to display.

**Comment by tohuynh** [comment]
> Similar to the backend PR linked, I would make it a try catch. Or if you wanted to be really fancy, have a transcript renderer map. Where given the transcript format string it returns the content ready to display.

Thanks for this recommendation. I'm using the transcript renderer map. Here's a preview of what speaker-turn blocks looks like.

![image](https://user-images.githubusercontent.com/37560480/71705868-63be9480-2d96-11ea-9a05-8a08f801d91f.png)

Any thoughts?

**Comment by evamaxfield** [comment]
This already looks awesome. I only have nitpicky things.

Nitpicky things:
1. I think if the speaker is an empty string instead of enumerating the speaker, just make it say "New Speaker"?
2. Not a part of this issue or upcoming PR, but I am starting to notice that maybe the event details, both the transcript, the voting records, and the minutes content width should be smaller. The content looks odd when the video is cutting off the upper corner. In my opinion anyway. If you agree I will make another issue for it that I think even I can solve because it should just be css changes.

**Comment by evamaxfield** [comment]
Mind if I send this for feedback by UX peeps too?

**Comment by tohuynh** [comment]
No, not at all.

1. The speaker is just fake data. I won't show speaker at all if it is unknown.
2. Sure, add screenshots too please.

**Comment by evamaxfield** [comment]
1. Meh I would still say "New Speaker" when it is an empty string but will hear back from others.
2. Sounds good.

**Comment by tohuynh** [comment]
![image](https://user-images.githubusercontent.com/37560480/71706504-28be6000-2d9a-11ea-8dac-4d95556e7d36.png)

This one is for `timestamped-sentences`. I could use any input on that too.

**Comment by evamaxfield** [comment]
I think for `timestamped-sentences` can we keep the current render? Having a card per sentence makes it feel like a lot is going on.

**Comment by tohuynh** [comment]
Ok, will switch back.

**Comment by evamaxfield** [comment]
Resolved in #57
