### ISSUE TITLE
Duplicate council city member.

### ISSUE THREAD

**Issue by alimon808** [CouncilDataProject/seattle_v2#62]
## Description
On the people page, multiple cards are displayed for the same member (e.g., Dan Straus, Adrew Lewis, Tammy J Morales).

## Expected Behavior
Show only one card per distinct council member.

**Comment by tohuynh** [comment]
This is more of a back-end issue. [#125](https://github.com/CouncilDataProject/cdptools/issues/125) addresses this bug.

**Comment by evamaxfield** [comment]
Closing here as this is an issue with back-end tooling.
