### ISSUE TITLE
Show mini player only when the main player is no longer visible.

### ISSUE THREAD

**Issue by alimon808** [CouncilDataProject/seattle_v2#67]
## Description
The place holder of the main player is visible when the mini player is active.  

## Expected Behavior
Only display the mini player when the main player is no longer visible.   Possible solution is to move the `Visibility` component below the `PlayerContainer` component.  

## Reproduction
Scroll down the event page until the top of the main player hits the top of the page.

**Comment by evamaxfield** [comment]
Resolved by #68
