### ISSUE TITLE
Choosing "Sort By" without choosing "Sort Order" does not sort entries

### ISSUE THREAD

**Issue by john-patterson** [CouncilDataProject/seattle_v2#80]
## System and Software
* Operating System: macOS Catalina Version 10.15.5 (19F101)
* Web Browser: Safari Version 13.1.1 (15609.2.9.1.2)
  and Chrom 83.0.4103.116

## Page or Route
* Link: https://councildataproject.github.io/seattle/#/search?q=tear+gas

## Description
When choosing a new sort from either a default or "Clear"ed state, no default sorting order is implied and neither radio button is selected. The "Save" button also does not validate that a sorting order was chosen to enable itself. If you "Save" without specifying an order, the sort has no effect on the data set.

## Notes
Here are two suggestions to solve this, either:
* Imply a default sort order by selecting one of the radio components at page load or after clear

or

* Disable the "Save" button if no valid sorting selection is made

**Comment by evamaxfield** [comment]
Hey @john-patterson thanks for reporting the issue! How would you feel about #77 
Which drops the sort options to simply two categories: "Sort by Relevance" and "Sort by Date" both descending.

@tohuynh want to quickly tackle this one?

**Comment by john-patterson** [comment]
@JacksonMaxfield I think it makes sense that I wouldn't want to sort by Committee name if I can already filter by it.

Relevancy sorting seems like it should always be done descending. I can't picture ever wanting to know what the least relevant hit is.

Maintaining Asc & Desc sort for dates seems to make sense, though. I could want to know when a topic was first mentioned and find the preliminary discussions around it, but I might also want to find the latest news on a topic.

**Comment by evamaxfield** [comment]
Gotcha. At the bare minimum I think we can drop it to just the two sort options. I don't know how to design basically one option that is a single choice and one option that has sub choices. Will talk to UX designers about it and hopefully make a decision and have something updated later this week.

**Comment by john-patterson** [comment]
@JacksonMaxfield by no means a UX expert myself, but here are my ideas:

## Descriptions

1.  "Sort by relevancy descending" is just the default sort when no other sort is applied. If you don't like hiding that decision from the user, including a text blurb: "Currently sorting by most relevant" makes it explicit.

2.   You could turn the UI for sorting based on date into three options: "Do not sort by date" (or "Sort by Relevancy"), "Sort by latest first," and "Sort by earliest first".

3.   Sort by date can be a checkbox, a dropdown for Asc/Desc can appear if the checkbox is enabled.
 
4.   The search result page could be more table-like. Relevancy percentage and date could be columns. Clicking the column header would sort by that column and add an up or down arrow indicating Asc or Desc. Clicking the header again would change between Asc and Desc and change the direction of the arrow on that column header. For simplicity, you can only ever sort by one column.


EDIT: I have some mocks.
## Diagrams

### (1) and (2)
(1) and (2) are reducible to this:
![image](https://user-images.githubusercontent.com/17716252/85958891-02930a80-b94e-11ea-92e6-b49243c39348.png)

### (3)
(3) I'm picturing something like this:
![image](https://user-images.githubusercontent.com/17716252/85958900-13dc1700-b94e-11ea-92b0-31c1b8062be1.png)

transitioning to

![image](https://user-images.githubusercontent.com/17716252/85958907-1a6a8e80-b94e-11ea-9f66-9b1c8b547666.png)

### (4)
(4) I chose to sort on Relevancy and Meeting Name in this mockup purely for ease of getting a mock.

Here's no ordering:
![image](https://user-images.githubusercontent.com/17716252/85959574-20fb0500-b952-11ea-888e-e582bd97dfe0.png)

Once you click "Relevancy", the screen becomes this. By Relevancy, ascending:
![image](https://user-images.githubusercontent.com/17716252/85959581-2bb59a00-b952-11ea-966c-6ad7a71fdf5a.png)

Once you click "Relevancy" again, the screen becomes this. By Relevancy, descending:
![image](https://user-images.githubusercontent.com/17716252/85959590-340dd500-b952-11ea-804c-e1d80a2111f9.png)

Once you click "Meeting Name", the screen becomes this. By Meeting Name, ascending:
![image](https://user-images.githubusercontent.com/17716252/85959631-5bfd3880-b952-11ea-9c94-2672739a6d5c.png)

And so on.

**Comment by evamaxfield** [comment]
Woah! Thanks for these. I hadn't thought about simply including the third option of "Newest First" and "Oldest First" I think I like that idea the most. Keep's it simple. Will talk it over with the UX team and show them these.

**Comment by evamaxfield** [comment]
Adding on to this, I think the list of sort options should probably be:

* Most Relevant (weighted by recency)  _This would be the default and is currently unimplemented but planned_
* Most Relevant (unweighted)
* Newest First
* Oldest First

**Comment by evamaxfield** [comment]
Alright update on this!

We are going to go with the following:
* Most Relevant
* Newest First
* Oldest First

Most Relevant will be weighted by recency

Sound good?

**Comment by tohuynh** [comment]
Sounds good. The default is going to be Most Relevant. What do you think should happen if the users click 'Clear"? The default becomes selected or none is selected (but events are still sorted by Most relevant)?

**Comment by evamaxfield** [comment]
I thought we were just going to go with the `cdp-instance` implementation which is just radio buttons right? So there wouldn't be a clear button. Or can we have it be a dropdown instead of radio buttons? That way one is always selected

**Comment by tohuynh** [comment]
OK, currently I made it so that all the filter popups have Clear and Save buttons. I can change it so that SelectSorting Popup won't have Clear and Save buttons.

**Comment by evamaxfield** [comment]
That would be perfect. Thanks! I will work on getting npm publishing setup.

**Comment by john-patterson** [comment]
Sounds good to me!

**Comment by evamaxfield** [comment]
@john-patterson thanks for reporting the original issue. The changes are now deployed on the website. Thanks to @tohuynh for fixing :rocket:
